version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
    - "8098:80"
    links:
      - fpm
    volumes:
      - ../src:/var/www/nixlibrary
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
        - ../src:/var/www/nixlibrary
    links:
        - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: nixtest
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:8081"
